### PR TITLE
Move Some Drawings into Dropdowns

### PR DESCRIPTION
**Pull request by gregziegan**
# Demo
screen recording 2017-04-27 at 10 43 am

# Ideas

* ~Close open drawing dropdowns when you've entered the canvas?~
* Hold and click to toggle dropdown?
* ~Right click to toggle dropdown?~
* ~Separate button to toggle?~

# Further questions from this approach

1) Should there be two columns? We have 320px max-height, could it be a single column?
2) Is a dropdown over the canvas annoying? Should we present them directed up or down?

### CODE REVIEW

**Comment by gregziegan** [comment]
@alanhogan, thoughts?

**Comment by alanhogan** [comment]
OK!

First let me observe a bug: In Safari but not Chrome, the menu is too far to the right ~thanks to a margin property~

screen shot 2017-04-23 at 5 06 50 pm

I think it's because you have a `position: absolute` item with no `left` (or `right`) properties inside of a `display: flex` element, and the browsers have different ways to handle this, with Safari positioning the item after the first element in its container. `left: 0` fixes it and makes the browsers consistent. (although you should note the parent element is does not have positioning context, so `top: 0` sends the menu to the top of your app. fix, if desired, with `pos: rel` on `.dropdown-things`)

OK, on to the bigger picture…

1) I dislike like how the sub-menu is positioned. The way it perfectly aligns to, and obscures, the underlying layer of buttons make it not obvious at a glance what is what. Here is an improvement, not that I think it's perfect…

    screen shot 2017-04-23 at 5 14 02 pm
    screen shot 2017-04-23 at 5 14 58 pm
    screen shot 2017-04-23 at 5 15 07 pm


2) After playing with it, I think I agree that the simple use-case of using the menu root to activate the default shape feels impeded by the way the menu is left lingering and covering part of the content. I suspect the long-press-or-right-click invocation approach would be better — certainly it avoids this problem. Hopefully it is discoverable enough. The Skitch approach has advantages, too.

3) Minor note: Esc should close the menu.

4) Suggested default shape: Roundrect. [Round Rects Are Everywhere!](http://www.folklore.org/StoryView.py?project=Macintosh&story=Round_Rects_Are_Everywhere.txt) is a beautiful piece of computer history, but by way of actual argument: They are more pleasing to look at than sharp rects and less problematically mis-matched to typical content than ellipses

**Comment by gregziegan** [comment]
To the bug: working on it.

1. Sure, but we should be consistent too and do it for all dropdowns. Perhaps: add a little triangle on the border of the dropdown. Also, position it point it to the bottom right corner of the button that toggles the dropdown

2. I will try long press. A problem I see, however. The bottom right corner arrow on the buttons should indicated a consistent pattern for accessing dropdowns. On fill, stroke, etc, it's a click. These two would be special cased with a hold.

3. easy, can't believe i forgot

4. into it

**Comment by alanhogan** [comment]
Agreed with your concern on #2. Maybe we just remove the triangle from the pure-menu items.

**Comment by alanhogan** [comment]
I’m sure this branch has some known issues, but this one is particularly noteworthy as the meaning of the icon is compromised:
screen shot 2017-04-27 at 11 04 26 pm

**Comment by gregziegan** [comment]
@alanhogan fixed this ^ with 5d2f94f

Placing `mask` in the `defs` solved this for Safari. I also centralized the `defs` across the app. Annoying to have them be added and removed with the vdom diffs. They're basically always 
globals that don't get mutated

**Pull request merged**
